Update shippable.yml

diff --git a/shippable.yml b/shippable.yml
--- a/shippable.yml
+++ b/shippable.yml
@@ -47,7 +47,22 @@ build:
     - echo FOO=$FOO
     - printenv
     - virtualenv --version #15.1.0
-    - if [ $SHIPPABLE_PYTHON_VERSION == "pypy" & $ENV == "valueFromMatrixIncludeNodeU16" ]; then echo 'success'; else testfail; fi
+    - |
+      if [ ! $SHIPPABLE_PYTHON_VERSION == "pypy" && $ENV == "valueFromMatrixIncludeNodeU16" ]; then
+        echo "success"
+        exit 1
+        else
+          testfail        
+      fi
+    #- |
+    #  if [ ! -z "$TEST_CACHE" ]; then
+    #    . /tmp/cache/cache.sh
+    #    if [ "$FOO" != "BAR" ]; then
+    #      echo "Cache is not working"
+    #      exit 1
+    #    fi
+    #  fi
+    #- if [ $SHIPPABLE_PYTHON_VERSION == "pypy" & $ENV == "valueFromMatrixIncludeNodeU16" ]; then echo 'success'; else testfail; fi
     - docker pull shippabledocker/sample_node_pvt:ecr
     
 integrations:
